spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://192.168.64.146:9092/~/h2/data/test'
    username: sa
    password:
  datasource.hikari:
    connection-timeout: 5000
    maximum-pool-size: 5

management:
  endpoint:
    health:
      show-details: always